CREATE TABLE s (v);
INSERT INTO s VALUES (CAST(x'41eda08042' AS TEXT));
CREATE TABLE o (v);
INSERT INTO o VALUES (CAST(x'c080' AS TEXT));
CREATE TABLE p (v);
INSERT INTO p VALUES (CAST(x'f4908080' AS TEXT));
CREATE TABLE n ("éé" TEXT);
INSERT INTO n VALUES (CAST(x'c3a9ff' AS TEXT));
