CREATE TABLE g (a INTEGER, b AS (a * 2), c AS (a || 'x') STORED);
INSERT INTO g (a) VALUES (1);
INSERT INTO g (a) VALUES (2);
CREATE TABLE s (i INTEGER, t TEXT, a ANY) STRICT;
INSERT INTO s VALUES (1, 'x', 2.5);
