CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, v);
INSERT INTO t (v) VALUES ('a');
INSERT INTO t (v) VALUES ('b');
CREATE VIEW vw AS SELECT * FROM t;
CREATE INDEX ix ON t (v);
CREATE TRIGGER tr AFTER INSERT ON t BEGIN SELECT 1; END;
ANALYZE;
