CREATE TABLE plain (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, total REAL GENERATED ALWAYS AS (id * 1.5) VIRTUAL);
INSERT INTO plain (name) VALUES ('one'), ('two');
CREATE TABLE kv (k TEXT PRIMARY KEY, v BLOB) WITHOUT ROWID;
INSERT INTO kv VALUES ('a', X'00FF'), ('b', NULL);
CREATE VIEW plain_view AS SELECT name FROM plain;
