<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>driftbuster</AssemblyName>
    <RootNamespace>DriftBuster.Cli</RootNamespace>
    <Version>$(DriftBusterCoreVersion)</Version>
    <AssemblyVersion>$(DriftBusterCoreVersion)</AssemblyVersion>
    <FileVersion>$(DriftBusterCoreVersion)</FileVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DriftBuster.Cli.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\gui\DriftBuster.Backend\DriftBuster.Backend.csproj" />
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>
</Project>
