
    <Project DefaultTargets="Build;Pack"
             ToolsVersion="15.0"
             xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <Import Project="shared.props" />
      <Import Project="shared.props" />
      <Target Name="Build" />
      <Target Name="Pack" />
    </Project>
    