using DriftBuster.Backend.Diff;
using DriftBuster.Backend.Sql;

namespace DriftBuster.Backend.Tests.Sql;

/// <summary>
/// fixtures/sql/sample.sqlite is generated by <see cref="SqlTestDatabase.CreateSampleDatabase"/> and committed. Regenerating it must give
/// the committed bytes; after a change to the helper or to the bundled SQLite library, set <c>DRIFTBUSTER_WRITE_SQL_FIXTURE=1</c> for one
/// run of this test to rewrite the file.
/// </summary>
public sealed class SqlSampleFixtureTests : IDisposable
{
    private readonly DirectoryInfo _tmp = Directory.CreateTempSubdirectory("driftbuster-sql-fixture-");

    public void Dispose() => _tmp.Delete(recursive: true);

    [Fact]
    public void RegeneratingTheSampleDatabaseYieldsTheCommittedBytes()
    {
        var first = SqlTestDatabase.CreateSampleDatabase(Path.Combine(_tmp.FullName, "first.sqlite"));
        var second = SqlTestDatabase.CreateSampleDatabase(Path.Combine(_tmp.FullName, "second.sqlite"));
        File.ReadAllBytes(second).Should().Equal(File.ReadAllBytes(first), "generation is deterministic");

        if (string.Equals(Environment.GetEnvironmentVariable("DRIFTBUSTER_WRITE_SQL_FIXTURE"), "1", StringComparison.Ordinal))
        {
            File.Copy(first, SqlTestDatabase.SampleFixture, overwrite: true);
        }

        File.ReadAllBytes(SqlTestDatabase.SampleFixture).Should().Equal(
            File.ReadAllBytes(first),
            "fixtures/sql/sample.sqlite must be what the helper generates (DRIFTBUSTER_WRITE_SQL_FIXTURE=1 rewrites it)");
    }
}
