using System.Globalization;
using System.Numerics;

using Microsoft.Data.Sqlite;

using SQLitePCL;

namespace DriftBuster.Backend.Tests.Sql;

/// <summary>
/// Builds SQLite databases for the SQL tests: each step one
/// statement stepped to completion in autocommit mode, parameters bound as <c>sqlite3</c> binds them (int as INTEGER, float as REAL, so
/// NaN stores NULL, str as UTF-8 TEXT, bytes as BLOB, None as NULL).
/// </summary>
internal static class SqlTestDatabase
{
    /// <summary>The committed sample database, generated by <see cref="CreateSampleDatabase"/>.</summary>
    public static string SampleFixture => RepoPaths.Fixtures("sql", "sample.sqlite");

    /// <summary>
    /// The sample database: the <c>accounts</c> table fixtures/sql/README.md
    /// documents, created in autocommit mode, then two rows inserted in one transaction (<c>sqlite3</c>'s implicit <c>BEGIN</c> before the
    /// first INSERT, then <c>commit()</c>).
    /// </summary>
    public static string CreateSampleDatabase(string path)
    {
        Build(
            path,
            [
                "CREATE TABLE accounts (id INTEGER PRIMARY KEY, email TEXT, secret TEXT, balance REAL)",
                "BEGIN",
                Step("INSERT INTO accounts (email, secret, balance) VALUES (?, ?, ?)", "alice@example.com", "token-1", 42.5),
                Step("INSERT INTO accounts (email, secret, balance) VALUES (?, ?, ?)", "bob@example.com", "token-2", 13.75),
                "COMMIT",
            ]);
        return path;
    }

    /// <summary>A step with parameters, in the <c>[sql, [params]]</c> shape.</summary>
    public static List<object?> Step(string sql, params object?[] parameters) => [sql, parameters.ToList()];

    /// <summary>Runs every step against <paramref name="path"/>, creating the file when it is missing.</summary>
    public static void Build(string path, IEnumerable<object?> steps)
    {
        var connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = path,
            Mode = SqliteOpenMode.ReadWriteCreate,
            Pooling = false,
        }.ToString();
        using var connection = new SqliteConnection(connectionString);
        connection.Open();
        foreach (var step in steps)
        {
            switch (step)
            {
                case string sql:
                    Execute(connection.Handle!, sql, []);
                    break;
                case List<object?> { Count: 2 } pair when pair[0] is string sql && pair[1] is List<object?> parameters:
                    Execute(connection.Handle!, sql, parameters);
                    break;
                default:
                    throw new InvalidDataException($"unsupported setup step {step}");
            }
        }
    }

    /// <summary>Applies each <c>{"find": hex, "replace": hex}</c> patch to the closed file; <c>find</c> must occur exactly once.</summary>
    public static void Patch(string path, IEnumerable<(byte[] Find, byte[] Replace)> patches)
    {
        var data = File.ReadAllBytes(path);
        foreach (var (find, replace) in patches)
        {
            var at = data.AsSpan().IndexOf(find);
            if (at < 0 || data.AsSpan(at + 1).IndexOf(find) >= 0)
            {
                throw new InvalidDataException($"patch {Convert.ToHexString(find)} does not occur exactly once in {path}");
            }

            data = [.. data[..at], .. replace, .. data[(at + find.Length)..]];
        }

        File.WriteAllBytes(path, data);
    }

    private static void Execute(sqlite3 db, string sql, IReadOnlyList<object?> parameters)
    {
        Check(db, raw.sqlite3_prepare_v2(db, sql, out var statement));
        using (statement)
        {
            for (var index = 0; index < parameters.Count; index++)
            {
                Check(db, Bind(statement, index + 1, parameters[index]));
            }

            int rc;
            while ((rc = raw.sqlite3_step(statement)) == raw.SQLITE_ROW)
            {
            }

            if (rc != raw.SQLITE_DONE)
            {
                Check(db, rc);
            }
        }
    }

    private static int Bind(sqlite3_stmt statement, int index, object? value) => value switch
    {
        null => raw.sqlite3_bind_null(statement, index),
        int number => raw.sqlite3_bind_int64(statement, index, number),
        long number => raw.sqlite3_bind_int64(statement, index, number),
        BigInteger number => raw.sqlite3_bind_int64(statement, index, (long)number),
        double number => raw.sqlite3_bind_double(statement, index, number),
        string text => raw.sqlite3_bind_text(statement, index, text),
        byte[] bytes => raw.sqlite3_bind_blob(statement, index, bytes),
        _ => throw new InvalidDataException($"unsupported parameter {value}"),
    };

    private static void Check(sqlite3 db, int rc)
    {
        if (rc != raw.SQLITE_OK)
        {
            throw new InvalidOperationException(string.Create(CultureInfo.InvariantCulture, $"SQLite {rc}: {raw.sqlite3_errmsg(db).utf8_to_string()}"));
        }
    }
}
