alphabet𝐀 one two three four five six seven eight
bravo𝐁 one two three four five six seven eight nine
charlie𝐂 one two three four five six seven eight
delta𝐃 one two three four five six seven eight nine ten
